server:
  port: 8889
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-product?serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:org/example/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: org.example.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
